# Generated by Django 4.2.7 on 2024-12-08 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_history_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 19, 6, 11, 950624, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
